export const ENV_VARS = {
    SMTP_PORT:'SMTP_PORT',
    SMTP_HOST:'SMTP_HOST',
    SMTP_USER:'SMTP_USER',
    SMTP_PASSWORD:'SMTP_PASSWORD',
    SMTP_FROM: 'SMTP_FROM',

    FRONTEND_DOMAIN: 'FRONTEND_DOMAIN',
    BACKEND_DOMAIN: 'BACKEND_DOMAIN',
    JWT_SECRET: 'JWT_SECRET',

    CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
    CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
    CLOUDINARY_API_PROJECT_NAME: 'CLOUDINARY_API_PROJECT_NAME',
    FILE_STORAGE_STRATEGY: 'FILE_STORAGE_STRATEGY',
}